### ISSUE TITLE
[Task] 서버 제작

### ISSUE THREAD

**Issue by EuilimChoi** [codestates/everyfootball#11]
### TODO
1. [ ] MVC 에 따른 폴더 정리
2. [ ] 서버 코드 작성
3. [ ] 각 엔드 포인트에 따른 파일 작성
4. [ ] 각 엔드 포인트 데이터 베이스 연결 확인
5. [ ] 각 엔드 포인트에 요청 수행 여부 확인
6. [ ] 각 엔드 포인트 요청사항 제작
