### ISSUE TITLE
Todo list :

### ISSUE THREAD

**Issue by EuilimChoi** [codestates/everyfootball#2]
# 프론트엔드

 ## 회원가입 페이지
- [ ] 아이디 중복확인 버튼 구현
- [ ] 중복확인 버튼을 누르면 DB에 있는 아이디정보와 일치하는 데이터가 있는지 확인(백엔드)
- [ ] 아이디가 중복되는 경우 ‘중복된 ID입니다.’ 문구를 띄우기
- [ ] 중복되지 않은 경우 문구를 숨기기 
- [ ] 비밀번호와 비밀번호확인  일치여부를 검사
  - [ ]     비밀번호 확인창을 벗어났을때 일치여부를 확인 
  - [ ]     일치하지 않는경우 ‘비밀번호가 일치하지 않습니다.’ 문구를 띄우기
  - [ ]     일치하는 경우 문구를 숨기기 
- [ ] 회원가입, 로그인 및 회원정보 수정 시 유효성 검사, 
  - [ ]     유효하지 않는 경우 ‘비밀번호는 영어,숫자,특수문자의 조합이어야 합니다.’ 문구를 띄우기
  - [ ]     유효한 경우 문구를 숨기
- [ ] 아이디, 비밀번호, 이름, 성별, 전화번호는 필수입력
- [ ] 포지션, 선호경기시간, 선호경기위치 는 선택입력
- [ ] 성별은 남,여 2가지 중 하나를 선택하도록 구현
- [ ] 가입버튼을 눌럿을때 가입조건을 만족하면 DB에 회원정보를 저장하도록 합니다.(백엔드)
- [ ] 가입 버튼을 눌럿을때 회원가입에 성공하면 메인페이지로 이동합니다.

 ## 메인 페이지
- [ ] 상단 헤더에 네비게이션 구현 (메인, 기록실, FAQ, 마이페이지(로그인 했을경우), 로그인페이지 이동링크, 로그아웃 버튼)
- [ ] 네비게이션에는 메인,기록실,FAQ를 구현
- [ ] 헤더 우측 상단에는 로그인,로그아웃,마이페이지 버튼을 구현
- [ ] 모집중인 경기 목록을 표시.(시간, 장소, 성별, 참여인원, 신청버튼)
- [ ] 신청 버튼을 눌렀을때 상세매치UI페이지로 이동하도록 구현 
- [ ] 하단 푸터에 사이트맵, 사업자정보를 표시

## 구체적 매치 정보
- [ ] 구장 이미지 및 지도 표시
- [ ] 구장 상세 사항 표시
- [ ] 선수정보
  - [ ]  신청하기 버튼 클릭 시 선수 정보에 내용 표시
  - [ ]  신청 완료 후 신청하기 버튼이 취소하기 버튼으로 변경
  - [ ]  취소하기 버튼 클릭 시 선수 정보에 내용 삭제
  - [ ]  취소 완료 후 취소하기 버튼이 신청하기 버튼으로 변경

## 레코드 보드

- [ ]  주요 부문 랭킹
  - [ ]   각 항목 별로 제일 높은 수의 유저네임과 해당 항목 표시
- [ ]  선수 기록
  - [ ]   득점 순으로 정렬하여 선수 정보 표시

## 로그인

- [ ] JWT를 이용한 로그인 구현 | 필수 | ★
- [ ] OAuth 2.0을 이용한 소셜 로그인 | 권장 | ★

## userinfo

- [ ] 마이페이지를 통해 사용자 개인정보 수정, 회원탈퇴 기능 제공 | 필수 | 프론트엔드 | ★ |
- [ ] 회원정보 수정 시 유효성 검사 | 필수 | 프론트엔드 | ★ |

# 백엔드

로그인 :

- [ ] JWT를 이용한 로그인 구현 | 필수 | ★
- [ ] OAuth 2.0을 이용한 소셜 로그인 | 권장 | ★
- [ ] 회원가입, 로그인, 로그아웃, 마이페이지, 회원탈퇴 기능 구현 | 필수 | 프론트엔드, 백엔드 | ★ |

회원가입 :
- [ ] JWT를 이용한 로그인 구현 | 필수 | ★
- [ ] 회원가입, 로그인, 로그아웃, 마이페이지, 회원탈퇴 기능 구현 | 필수 | 프론트엔드, 백엔드 | ★

메인 :
- [ ] N:M (다대다) 관계 설정 | 필수 | ★
- [ ] ERD (DB Diagram) 작성 | 필수 | ★
- [ ] API 작성 툴 (Swagger, Postman, Gitbook API) 사용 | 필수 | ★★

유저 정보 :
- [ ] N:M (다대다) 관계 설정 | 필수 | ★
- [ ] ERD (DB Diagram) 작성 | 필수 | ★
- [ ] API 작성 툴 (Swagger, Postman, Gitbook API) 사용 | 필수 | ★★

구체적 매치 정보 :
- [ ] N:M (다대다) 관계 설정 | 필수 | ★
- [ ] ERD (DB Diagram) 작성 | 필수 | ★
- [ ] API 작성 툴 (Swagger, Postman, Gitbook API) 사용 | 필수 | ★★

레코드 보드:
- [ ] N:M (다대다) 관계 설정 | 필수 | ★
- [ ] ERD (DB Diagram) 작성 | 필수 | ★
- [ ] API 작성 툴 (Swagger, Postman, Gitbook API) 사용 | 필수 | ★★

FAQ:
- [ ] API 작성 툴 (Swagger, Postman, Gitbook API) 사용 | 필수 | ★★
